"""empty message

Revision ID: 110a29eb5b7
Revises: 48b020d0b10
Create Date: 2015-12-03 09:01:35.162973

"""

# revision identifiers, used by Alembic.
revision = '110a29eb5b7'
down_revision = '48b020d0b10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_file', sa.String(length=200), nullable=True),
    sa.Column('saved_file', sa.String(length=200), nullable=True),
    sa.Column('proj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proj_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_file_saved_file'), 'user_file', ['saved_file'], unique=False)
    op.create_index(op.f('ix_user_file_uploaded_file'), 'user_file', ['uploaded_file'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_file_uploaded_file'), table_name='user_file')
    op.drop_index(op.f('ix_user_file_saved_file'), table_name='user_file')
    op.drop_table('user_file')
    ### end Alembic commands ###
