"""empty message

Revision ID: 15c1c70ef9a
Revises: 4ed729f6cf0
Create Date: 2015-08-13 15:01:23.689894

"""

# revision identifiers, used by Alembic.
revision = '15c1c70ef9a'
down_revision = '4ed729f6cf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
