"""empty message

Revision ID: 194a4d3d9aa8
Revises: 50dc65cc531
Create Date: 2016-05-20 12:19:43.729443

"""

# revision identifiers, used by Alembic.
revision = '194a4d3d9aa8'
down_revision = '50dc65cc531'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_access',
    sa.Column('fa_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['user_file.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('fa_id')
    )
    op.drop_constraint('user_file_proj_id_fkey', 'user_file', type_='foreignkey')
    op.drop_column('user_file', 'proj_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_file', sa.Column('proj_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_file_proj_id_fkey', 'user_file', 'projects', ['proj_id'], ['id'])
    op.drop_table('file_access')
    ### end Alembic commands ###
