"""empty message

Revision ID: 2cd591d2bd3
Revises: 557dc22e30a
Create Date: 2015-08-14 15:17:26.948039

"""

# revision identifiers, used by Alembic.
revision = '2cd591d2bd3'
down_revision = '557dc22e30a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
