"""empty message

Revision ID: 3d2be5f14b1
Revises: 15c1c70ef9a
Create Date: 2015-08-14 09:22:38.357633

"""

# revision identifiers, used by Alembic.
revision = '3d2be5f14b1'
down_revision = '15c1c70ef9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access', sa.Column('test', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_access', 'test')
    ### end Alembic commands ###
