"""empty message

Revision ID: 4fd3045cf2b
Revises: 3d2be5f14b1
Create Date: 2015-08-14 10:38:10.267053

"""

# revision identifiers, used by Alembic.
revision = '4fd3045cf2b'
down_revision = '3d2be5f14b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_access', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
