"""empty message

Revision ID: 557dc22e30a
Revises: 55f06831c1b
Create Date: 2015-08-14 14:54:33.593503

"""

# revision identifiers, used by Alembic.
revision = '557dc22e30a'
down_revision = '55f06831c1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
