"""empty message

Revision ID: 55f06831c1b
Revises: 4fd3045cf2b
Create Date: 2015-08-14 14:53:09.023511

"""

# revision identifiers, used by Alembic.
revision = '55f06831c1b'
down_revision = '4fd3045cf2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    ### end Alembic commands ###
