"""empty message

Revision ID: 5e7bf5b1f38b
Revises: 548dd7efc5c2
Create Date: 2016-06-14 12:46:54.549977

"""

# revision identifiers, used by Alembic.
revision = '5e7bf5b1f38b'
down_revision = '548dd7efc5c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_file_name', table_name='projects')
    op.drop_index('ix_projects_saved_file', table_name='projects')
    op.create_unique_constraint(None, 'projects', ['id'])
    op.drop_column('projects', 'file_name')
    op.drop_column('projects', 'saved_file')
    op.create_unique_constraint(None, 'user_access', ['id'])
    op.create_unique_constraint(None, 'user_file', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_file', type_='unique')
    op.drop_constraint(None, 'user_access', type_='unique')
    op.add_column('projects', sa.Column('saved_file', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='unique')
    op.create_index('ix_projects_saved_file', 'projects', ['saved_file'], unique=False)
    op.create_index('ix_projects_file_name', 'projects', ['file_name'], unique=False)
    ### end Alembic commands ###
