"""empty message

Revision ID: b4378cbfd74e
Revises: cbfd800c48bf
Create Date: 2017-01-04 11:46:34.734787

"""

# revision identifiers, used by Alembic.
revision = 'b4378cbfd74e'
down_revision = 'cbfd800c48bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_access', sa.Column('user_can_edit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_access', 'user_can_edit')
    # ### end Alembic commands ###
