"""empty message

Revision ID: cbfd800c48bf
Revises: 5e7bf5b1f38b
Create Date: 2016-06-14 12:47:27.381807

"""

# revision identifiers, used by Alembic.
revision = 'cbfd800c48bf'
down_revision = '5e7bf5b1f38b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
